export const pageElements = {
  homePage: 'https://automationteststore.com/',
  loginLink: 'a:contains("Login or register")',
  continueButton: 'button[title="Continue"]',
  firstNameInput: '#AccountFrm_firstname',
  lastNameInput: '#AccountFrm_lastname',
  emailInput: '#AccountFrm_email',
  telephoneInput: '#AccountFrm_telephone',
  addressInput: '#AccountFrm_address_1',
  cityInput: '#AccountFrm_city',
  postcodeInput: '#AccountFrm_postcode',
  countrySelect: '#AccountFrm_country_id',
  stateSelect: '#AccountFrm_zone_id',
  loginNameInput: '#AccountFrm_loginname',
  passwordInput: '#AccountFrm_password',
  confirmPasswordInput: '#AccountFrm_confirm',
  newsletterCheckbox: '#AccountFrm_newsletter0',
  agreeTermsCheckbox: 'input[name="agree"]',
  submitButton: 'button[title="Continue"]',
  alertError: '.alert.alert-error.alert-danger',
  loginNameField: 'input[name="loginname"]',
  passwordField: 'input[name="password"]',
  addToCartButtons: 'a[data-id]',
  cartMenu:'span.menu_text:contains("Cart")',
  checkoutButton: 'span.menu_text:contains("Checkout")',
  orderSuccessMessage: '.maintext',
  logoutButton: 'a[data-original-title="Logoff"]',
  searchInput: 'input#filter_keyword',
  productName: 'h1.productname',
  automationStore: 'img[alt="Automation Test Store"]', 
};
